import = ["/home/steph/.config/alacritty/dracula.toml"]

[window]
padding = { x = 5, y = 5 }
decorations = "full"

[font]
size = 11
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Back", action = "IncreaseFontSize"},
  { mouse = "Forward", action = "DecreaseFontSize"},
]
